### ISSUE TITLE
Changeable default Mime

### ISSUE THREAD

**Issue by DenisKolodin** [cybergeek94/mime_guess#11]
Lib's functions use `octet_stream` as default mime:

```rust
pub fn get_mime_type(search_ext: &str) -> Mime {
    get_mime_type_str(search_ext)
        .map(|mime| mime.parse::<Mime>().unwrap())
        .unwrap_or_else(octet_stream)
}
```

What about to make default mime changeable?
It's useful for HTML5 routing compatible servers to response with `text/html` for any non-existent url.

**Comment by cybergeek94** [comment]
Closed by #12 (functions added which return `None` instead of `application/octet-stream`)
