### ISSUE TITLE
Compile-time hashtable (build script/procedural macro)?

### ISSUE THREAD

**Issue by cybergeek94** [cybergeek94/mime_guess#13]
We could eliminate the need for a binary search by converting the extension -> MIME type mappings to a hashtable at compile time.

I see three different ways to do this:

* Use a build script to read mappings from a more suitable format, like JSON, and write them as a Rust module like they are now, but arranged in a hashtable.
     * Pros: 
         * Doable now with stable Rust
     * Cons:
         * Requires conversion of mappings to a more suitable format, like JSON.
         * Duplication of hashtable implementation between build script and crate code (they *could* use the same source files, though)

* Write a procedural macro to rearrange the MIME type mappings (in Rust)
    * Pros:
        * Current mapping list can remain
    * Cons:
        * Not doable in stable Rust, have to wait for stabilized procedural macros

* Compromise: a feature flag which enables the procedural macro and compile-time hashtable, but when disabled falls back to binary search.
    * Pros:
        * Current mapping list can remain
        * When disabled, will continue to work on stable Rust and the existing mappings will be untouched
        * Allows the user to choose between faster compiles or faster searches
    * Cons:
        * More complex to implement than procedural macros should/will be
        * Higher maintenance burden due to breakage on nightlies

* Pros for any approach:
    * Amortized constant-time searches (not as sensitive to the length of the list or key)
    * The list doesn't have to be hand-ordered or checked for case
* Cons:
    * Slower compile times (probably not by a whole lot, though)

I'm thinking it should use open-addressing so we don't have to deal with the indirection of chaining. Exactly which strategy to use is up for debate.

Thoughts? @DenisKolodin @LukasKalbertodt 

@jdm Would this be beneficial to Servo or is it inconsequential? The API wouldn't change, just compile and search times.

**Comment by Ryman** [comment]
Maybe relevant: https://github.com/sfackler/rust-phf#phf_codegen

**Comment by cybergeek94** [comment]
@Ryman that's actually pretty neat. We'll probably end up doing that with a build script if this is a desirable feature.

**Comment by cybergeek94** [comment]
So I went ahead and created an implementation of this using `phf_codegen`. On my laptop it went from 91ns/iter for the binary search impl down to 59ns/iter. That's a hell of a perf gain. Both are still insanely fast for an operation that probably won't be used too often, but I like that it doesn't require a strict ordering. I'll probably patch the build script to convert the extensions to lowercase as well.

**Comment by cybergeek94** [comment]
It is a breaking change since `MIME_TYPES` was previously exported. It will now be kept private.

**Comment by jdm** [comment]
This shouldn't impact Servo in any noticeably negative fashion.

**Comment by Ogeon** [comment]
I'm doing exactly this in Rustful. [This build script](https://github.com/Ogeon/rustful/blob/master/build/mime.rs) generates a table of `TopLevel`/`SubLevel` pairs from the Apache MIME list. It's then [included i the library](https://github.com/Ogeon/rustful/blob/8856c35cf528b455873f1525e57e8de0456491fb/src/file.rs#L7), where the parts are combined.

**Comment by cybergeek94** [comment]
Opened #14.

**Comment by cybergeek94** [comment]
Closed by #14.
