### ISSUE TITLE
Provide a reversed guess?

### ISSUE THREAD

**Issue by izgzhen** [cybergeek94/mime_guess#19]
Hi, I am thinking if it will be proper to provide a reversed guess in this crate, i.e. Mime => [Extension]. I found a similar thing [here](https://github.com/samuelneff/MimeTypeMap/blob/master/src/MimeTypes/MimeTypeMap.cs#L709), but this looks not the best semantics, which should return a list of possible extensions.

**Comment by cybergeek94** [comment]
This is a good idea, thanks!

**Comment by cybergeek94** [comment]
Feature complete in 1.7.0. Give it a try and let me know what you think!

**Comment by izgzhen** [comment]
Great job! You are so fast 😄. Actually I have a suggestion: it would be nice to be able to accept things like `video/*`, which is a simple match-all-pattern.

Actually, I am working on https://html.spec.whatwg.org/multipage/forms.html#attr-input-accept in servo, so it would be convenient to have. Thanks in advance if this sounds sensible to you.

**Comment by cybergeek94** [comment]
Actually it would have really helped if you had shared your use-case! I've yanked 1.7.0 so I can take this feature back to the drawing board. I think I can make it work as you like without any breaking changes, only changes internal to the crate!

I'm assuming you would like the returned slice sorted in lexographical order.

**Comment by izgzhen** [comment]
lexicographical order is sweet. Sorry that I didn't provide that piece of information beforehand. (First time hearded that we can yank a crate back though). Thanks again!

**Comment by cybergeek94** [comment]
@izgzhen Okay, a little design problem here. The primary issue is this:

If all extensions are sorted lexicographically within a `TopLevel` (e.g. all extensions for `video/*` are sorted), then each sublevel (e.g. `video/mpeg`) cannot return a contiguous slice, because its extensions would be potentially intermixed with those of its siblings.

If all extensions are sorted lexicographically for each `SubLevel`, then they will not be sorted when viewed from e.g. `video/*`.

if we ignore the need to return a slice, and instead use an opaque iterator type, then I believe I can uphold both of these properties.

Which do you prefer?

**Comment by izgzhen** [comment]
Just for the `accept` attribute case, sorted or not is really not of much of a problem in fact. And for more general consideration, in the slice case, it would be more natural to let them intermix IMO.

And yes, as you say, using an iterator will be more flexible though.

**Comment by cybergeek94** [comment]
@izgzhen Have a look at the changes in #20 and see if that will fit your needs.

As a consequence of the original sorting of the extensions -> MIME types map, extensions will be sorted lexicographically within sub-levels.

**Comment by izgzhen** [comment]
Cool, it works like a charm :D

**Comment by izgzhen** [comment]
@cybergeek94 How is it going now?

**Comment by cybergeek94** [comment]
Just waiting for Travis builds to finish on the PR, then will merge and publish.

**Comment by cybergeek94** [comment]
Published as `1.8.0`. Also feel free to update `mime` to `0.2.1` as I just got `SubLevel::OctetStream` added so that `mime_guess::octet_stream` doesn't require an allocation! I made sure that it will continue to work with `0.2.0`, and probably down to `0.1` as well.
