### ISSUE TITLE
Sync with upstream source

### ISSUE THREAD

**Issue by emosenkis** [cybergeek94/mime_guess#9]
[current list](https://github.com/cybergeek94/mime_guess/files/51362/mime_types.rs.txt)
[upstream list](https://github.com/cybergeek94/mime_guess/files/51361/MimeTypeMap.cs.txt)

**Comment by cybergeek94** [comment]
Can you provide a quick diff?

**Comment by emosenkis** [comment]
The two links are to files I uploaded as attachments to this issue - they're versions of the mappings files in this and the upstream repo that I modified to use the same formatting so that 'diff' can be used to compare them without any noise.

**Comment by cybergeek94** [comment]
That's actually a pretty significant diff. `gvimdiff` makes it much easier to see the edit distance and not just the lines that changed.

Thanks for those files. I'll update this soon.

**Comment by cybergeek94** [comment]
Closed with version `1.3.0`.
